### ISSUE TITLE
Backport requestAnimationFrame polyfill from jest-environment-jsdom

### ISSUE THREAD

**Issue by taion** [Micromeritics/jest-environment-jsdom-11.0.0#1]
Per https://github.com/facebook/jest/pull/4568, due to https://github.com/facebook/jest/issues/4545.

Needs to be in the Jest environment due to pending upstream issue https://github.com/tmpvar/jsdom/issues/1963.

**Comment by SimenB** [comment]
FWIW: https://github.com/tmpvar/jsdom/pull/1994

**Comment by taion** [comment]
Cool, so this is unnecessary if that lands upstream.
